### ISSUE TITLE
Failed to build on Windows.

### ISSUE THREAD

**Issue by tasuren** [libui-rs/libui#3]
Hi.
The following error occurs when trying to build an application for Windows using this crate. Is there something wrong with the setup?
I would appreciate a response if you have time.
```
$ cargo build

...

error: failed to run custom build command for `libui-ffi v0.2.0`

Caused by:
  process didn't exit successfully: `C:\Users\tasuren.TASUREN-SUB\Documents\src\app\a-synthe\target\debug\build\libui-ffi-b4b53d8a3b867764\build-script-build` (exit code: 101) 
  --- stdout
  git version 2.41.0.windows.1

  --- stderr
  fatal: not a git repository (or any of the parent directories): .git
  error: patch failed: windows/progressbar.cpp:9
  error: windows/progressbar.cpp: patch does not apply
  thread 'main' panicked at '"enum_(unnamed_at__/libui/ui_h_53_1)" is not a valid Ident', C:\Users\tasuren.TASUREN-SUB\.cargo\registry\src\index.crates.io-6f17d22bba15001f\proc-macro2-1.0.60\src\fallback.rs:791:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```
### Spec
```shell
$ rustup --version
rustup 1.26.0 (5af9b9484 2023-04-05)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.70.0 (90c541806 2023-05-31)`

$ cargo --version
cargo 1.70.0 (ec8a8a0ca 2023-04-25)

$ winget show LLVM
見つかりました LLVM [LLVM.LLVM]
バージョン: 16.0.4 # <-- **Version of LLVM**
公開元: LLVM
発行元 URL: https://github.com/llvm/llvm-project
発行元のサポート URL: https://github.com/llvm/llvm-project/issues
作成者: LLVM Project
モニカー: llvm
説明: The LLVM Project is a collection of modular and reusable compiler and toolchain technologies.
ホーム ページ: https://llvm.org
ライセンス: Apache License v2.0 with LLVM Exceptions
ライセンス URL: https://github.com/llvm/llvm-project/blob/llvmorg-16.0.0/LICENSE.TXT
リリース ノート URL: https://github.com/llvm/llvm-project/releases/tag/llvmorg-16.0.4
タグ:
  c
  c++
  clang
  lld
  lldb
  llvm
  objective-c
インストーラー:
  インストーラーの種類: nullsoft
  インストーラーのロケール: en-US
  インストーラーの URL: https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.4/LLVM-16.0.4-win64.exe
  インストーラーの SHA256: d9f879c6ea0db32c2e3eb570074ff8c74714bca6d5fe940a218909c74d5d4644
  リリース日: 2023-05-17
```
MSVC Version: 2015-2022 (14.36.32532.0)

## etc
I also did the same build for Windows using cargo xwin on a Mac, and the same error occurs in that case.

**Comment by nptr** [comment]
Thanks for the report. Interestingly the CI runs to completion.
Anyways, I'll investigate. The build script in libui-ffi/build.rs applies a (git) patch file to the underlying libui before building. That seems to fail for some reason.

**Comment by tasuren** [comment]
Thanks for the reply.
After a little investigation, I think it is possible that it is a dependency bug or something else.
First of all, the versions of bindgen and proc-macro2 that can be seen in the CI build logs are different from the versions at the time of build when I cloned this repository in my environment. The versions of bindgen and proc-macro2 are more up-to-date when built in my environment.
After I updated bindgen on `Cargo.toml` to the latest version `0.66`, I fixed some errors in libui code caused by the update, and the build succeeded in my environment.
Thus, it may be caused by a dependency.

Also, the libui that is updated by me is here: https://github.com/tasuren/libui

**Comment by nptr** [comment]
That might explain. I hope to get to have a look at it in the next days (..busy). The dependencies are to be updated anyways sooner or later. For 0.2.0 I wanted to keep everything still rust2018 (afaik) compatible like the old 'iui' was in case you wonder.

**Comment by nptr** [comment]
Version `0.3.0` is live on crates.io, with updated dependencies. It should work for you out of the box now and make your fork obsolete.
